# Generated by Django 6.0.3 on 2026-03-20 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(default='DE', max_length=64)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ds100', models.CharField(blank=True, max_length=24)),
                ('short_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DailyStationStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(choices=[('departure', 'Departure'), ('arrival', 'Arrival')], max_length=16)),
                ('stats_date', models.DateField()),
                ('total_trains', models.PositiveIntegerField(default=0)),
                ('average_delay', models.FloatField(default=0)),
                ('median_delay', models.FloatField(default=0)),
                ('on_time_ratio', models.FloatField(default=0)),
                ('delayed_over_5_ratio', models.FloatField(default=0)),
                ('maximum_delay', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='trains.station')),
            ],
            options={
                'ordering': ['-stats_date', 'station'],
                'unique_together': {('station', 'board_type', 'stats_date')},
            },
        ),
        migrations.CreateModel(
            name='TrainSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(choices=[('departure', 'Departure'), ('arrival', 'Arrival')], max_length=16)),
                ('record_uid', models.CharField(max_length=180, unique=True)),
                ('external_trip_id', models.CharField(blank=True, max_length=128)),
                ('train_name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('direction', models.CharField(max_length=255)),
                ('planned_time', models.DateTimeField()),
                ('updated_time', models.DateTimeField(blank=True, null=True)),
                ('delay_minutes', models.PositiveIntegerField(default=0)),
                ('platform', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(default='scheduled', max_length=40)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('service_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='trains.station')),
            ],
            options={
                'ordering': ['planned_time'],
                'indexes': [models.Index(fields=['station', 'board_type', 'planned_time'], name='trains_trai_station_87d10b_idx'), models.Index(fields=['station', 'board_type', 'service_date'], name='trains_trai_station_2b2121_idx'), models.Index(fields=['delay_minutes'], name='trains_trai_delay_m_4e30f8_idx')],
            },
        ),
    ]
